# Generated by Django 4.2.9 on 2024-01-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_age', models.CharField(max_length=30)),
            ],
        ),
    ]
